### PR TITLE
Add contributor name in issue text

### PR DESCRIPTION
**Pull request by Nilanshrajput**

### CODE REVIEW

**Review by jph00 — CHANGES_REQUESTED** [review]
Minor issue: looks like you didn't run `nbdev_build_lib`, or you have an older version of `nbdev`?

More substantive issue: I think issues don't always have assignees? In that case, I suspect we shouldn't include that section.

**Comment by jph00** [comment]
BTW please at-mention me so I don't miss your response :)

**Comment by Nilanshrajput** [comment]
@jph00 yup I didn't run the  nbdev_build_lib, will correct it. I just wanted to ask does this consider only Pull requests, in that case, we can point to the creator of the issue instead of assigned.

**Comment by jph00** [comment]
Yes that would be better.

**Comment by Nilanshrajput** [comment]
```root@:~/fastrelease# nbdev_build_lib
Converted 00_core.ipynb.
Converted 01_conda.ipynb.
Converted index.ipynb.
root@:~/fastrelease# nbdev_test_nbs
<IPython.core.display.HTML object>
<IPython.core.display.HTML object>
testing /root/fastrelease/01_conda.ipynb
testing /root/fastrelease/00_core.ipynb
testing /root/fastrelease/index.ipynb
<IPython.core.display.HTML object>
<IPython.core.display.HTML object>
<IPython.core.display.HTML object>
<IPython.core.display.HTML object>
All tests are passing!
root@:~/fastrelease# ```

Tests are passing locally not sure what's happening here

**Comment by Nilanshrajput** [comment]
@jph00  done (I guess do squash and merge, a lot of bad commits, and rebasing from vscodeserver is buggy)

**Comment by jph00** [comment]
Sorry I misunderstood your question. We have both issues and PRs. I'll try to figure out how to make this only apply to PRs.

**Pull request merged**
