### PR TITLE
Update Instructions

### PR DESCRIPTION
**Pull request by hamelsmu**
I updated the instructions

### CODE REVIEW

**Comment by jph00** [comment]
I'd suggest removing the end bit that bumps the version. You don't want to bump the version until you've actually created and uploaded pip/conda/etc packages. Generally you'd update the changelog first, so your packages will have the updated changelog included.

Overall, I'm not quite sure of the purpose of having these gh actions - what problem do you feel they solve? Seems to me that you really need to be in the terminal for your release process anyway, and moving over to a browser for some step seems clunky. And it's harder to automated.

I might well be missing something though!

**Comment by hamelsmu** [comment]
Yeah I was doing this incrementally.  This would have to include uploading to pypi and Conda but I haven’t done that yet.  Just curious wanted to know if I was on the right track.   I don’t want to slove a hypothetical problem so let’s just put this on pause, because automated release is not necessarily a problem I have either.   I’ll go ahead and delete all these Action files?  What do you think?

**Comment by jph00** [comment]
Yeah if you don't think it's solving a real problem either, then I agree, may as well delete them. Thanks for looking into this anyway! :)

**Comment by hamelsmu** [comment]
@jph00 merging the Actions

**Pull request merged**
